### ISSUE TITLE
Typo in docs on https://domain-shared-contacts-client.readthedocs.io/en/latest/usage.html

### ISSUE THREAD

**Issue by DALDEI** [rjoyal/domain_shared_contacts_client#15]
### Description

Doc Bug

### What I Did

```
Read the Docs, Tried to Use it
```
###

https://domain-shared-contacts-client.readthedocs.io/en/latest/usage.html

Two places  "--contact-details" is cited , the actual arguement is "--contact_details"

**Comment by goodtune** [comment]
Now that #17 is merged the documentation has been updated to correspond with the new command line interface, making this issue no longer relevant.
